---
name: AWS CloudFormation Deployment
on: workflow_dispatch
jobs:
  setup-repo:
    name: Setup Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
          echo "Checkout code."
  validate-code:
    needs: setup-repo
    name: Validate Template
    runs-on: ubuntu-latest
    steps:
      - name: CloudFormation Validate
        run: |
          echo "CloudFormation Validate"
          
      - name: Run Checkov Scan
        run: |
          echo "Run Checkov Scan"
