name: AWS CloudFormation Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        run: |
          echo "Checkout code."
